In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

- one hot encoding happens with hash mapping that's why we need to give vocabulary size explicitily.
- where as tokennizer is different scenario, it takes the values automatically depending on the size of unique words.
- we should not give vocabulary size less than actual unique size in one hot because, you might end up having same hash number for 2 different words. which will be a issue again.

In [4]:
voc_size = 10000

one_hot_sent = [one_hot(words,voc_size) for words in sent]
one_hot_sent

[[8940, 3476, 6340, 318],
 [8940, 3476, 6340, 6423],
 [8940, 7124, 6340, 7740],
 [9704, 9742, 6285, 4986, 6831],
 [9704, 9742, 6285, 4986, 1101],
 [6206, 8940, 7273, 6340, 5920],
 [9339, 2319, 6608, 4986]]

In [5]:
sent_length = 8
padded_sent = sequence.pad_sequences(one_hot_sent, padding='pre', maxlen=sent_length)
padded_sent

array([[   0,    0,    0,    0, 8940, 3476, 6340,  318],
       [   0,    0,    0,    0, 8940, 3476, 6340, 6423],
       [   0,    0,    0,    0, 8940, 7124, 6340, 7740],
       [   0,    0,    0, 9704, 9742, 6285, 4986, 6831],
       [   0,    0,    0, 9704, 9742, 6285, 4986, 1101],
       [   0,    0,    0, 6206, 8940, 7273, 6340, 5920],
       [   0,    0,    0,    0, 9339, 2319, 6608, 4986]])

- dim/output dim is the size of the vector for each word.
- you must give dim, because input_length only tells how long the sequence is — not how you want to represent the words.

In [6]:
dim=10

model = Sequential()
#Embedding(input_dim=voc_size, output_dim=10, input_length=sent_length)
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.predict(padded_sent)

1/1 [==============================] - 0s 69ms/step


array([[[-1.08389743e-02, -1.59063190e-03, -6.15670532e-03,
         -2.10177433e-02,  5.53566217e-03, -2.08806396e-02,
         -2.00743079e-02, -1.42371282e-02, -4.25534248e-02,
          3.93373482e-02],
        [-1.08389743e-02, -1.59063190e-03, -6.15670532e-03,
         -2.10177433e-02,  5.53566217e-03, -2.08806396e-02,
         -2.00743079e-02, -1.42371282e-02, -4.25534248e-02,
          3.93373482e-02],
        [-1.08389743e-02, -1.59063190e-03, -6.15670532e-03,
         -2.10177433e-02,  5.53566217e-03, -2.08806396e-02,
         -2.00743079e-02, -1.42371282e-02, -4.25534248e-02,
          3.93373482e-02],
        [-1.08389743e-02, -1.59063190e-03, -6.15670532e-03,
         -2.10177433e-02,  5.53566217e-03, -2.08806396e-02,
         -2.00743079e-02, -1.42371282e-02, -4.25534248e-02,
          3.93373482e-02],
        [ 1.96485035e-02, -5.61143085e-03,  4.48584557e-04,
          2.23685391e-02,  4.11937870e-02,  1.51708759e-02,
         -3.56135145e-02,  4.74494807e-02, -4.367787

In [10]:
model.predict(padded_sent[0])

1/1 [==============================] - 0s 163ms/step


array([[-0.01083897, -0.00159063, -0.00615671, -0.02101774,  0.00553566,
        -0.02088064, -0.02007431, -0.01423713, -0.04255342,  0.03933735],
       [-0.01083897, -0.00159063, -0.00615671, -0.02101774,  0.00553566,
        -0.02088064, -0.02007431, -0.01423713, -0.04255342,  0.03933735],
       [-0.01083897, -0.00159063, -0.00615671, -0.02101774,  0.00553566,
        -0.02088064, -0.02007431, -0.01423713, -0.04255342,  0.03933735],
       [-0.01083897, -0.00159063, -0.00615671, -0.02101774,  0.00553566,
        -0.02088064, -0.02007431, -0.01423713, -0.04255342,  0.03933735],
       [ 0.0196485 , -0.00561143,  0.00044858,  0.02236854,  0.04119379,
         0.01517088, -0.03561351,  0.04744948, -0.04367788,  0.03239517],
       [-0.01733184, -0.00636739, -0.01515295,  0.02635373,  0.00316525,
         0.01380474,  0.00716047, -0.04514898,  0.04645039,  0.0346764 ],
       [-0.00977794, -0.03586655,  0.01732698, -0.00507947, -0.0310859 ,
         0.02950497,  0.03258151,  0.02642499

- as we can see now we are getting each words vectors as 10 dimension values for 8 words.
- as we have zero for first 3 words, we are getting same vectors values for them.