# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

In [33]:
np_array = np.random.randint(1,20,size=(5,5))
np_array

array([[16, 12,  5, 18, 13],
       [18, 17,  3,  4,  6],
       [ 9,  4,  9, 16, 18],
       [12,  7,  5, 12,  5],
       [17,  6, 19,  4,  7]], dtype=int32)

In [61]:
np_array[:,2] = 1
np_array

array([[16, 12,  1, 18, 13],
       [18, 17,  1,  4,  6],
       [ 9,  4,  1, 16, 18],
       [12,  7,  1, 12,  5],
       [17,  6,  1,  4,  7]], dtype=int32)

In [31]:
# for n in range(0,5):
#     np_array[n][2] = 1
# np_array

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [66]:
np_array = np.random.randint(1,16,size=(4,4))
np_array

array([[ 4,  9, 13, 10],
       [ 2,  8, 15,  5],
       [ 7, 10,  1,  2],
       [ 1, 14,  8,  5]], dtype=int32)

In [74]:
np.fill_diagonal(np_array,0)
np_array

array([[ 0,  9, 13, 10],
       [ 2,  0, 15,  5],
       [ 7, 10,  0,  2],
       [ 1, 14,  8,  0]], dtype=int32)

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [83]:
np_array = np.random.randint(1,37,size=(6,6))
print(np_array)
print(np_array[2:5,1:4])

[[36 21 21  9 22 28]
 [20 31  8 23 19 18]
 [14 36 36  2 28 25]
 [30  7 32  8 26  5]
 [ 1  1 15  1 30 27]
 [22  6 12  6 27 29]]
[[36 36  2]
 [ 7 32  8]
 [ 1 15  1]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [88]:
np_array = np.random.randint(1,20,size=(5,5))
print(np_array)

[[10 19  4  5 12]
 [ 5  9  6 13 16]
 [ 3 12  2 15  8]
 [ 7 16  4  3 10]
 [ 2  9 11 12  4]]


In [110]:
np.concatenate((np_array[0,:],np_array[1:-1,-1],np_array[-1,:],np_array[1:-1:,0]))

array([10, 19,  4,  5, 12, 16,  8, 10,  2,  9, 11, 12,  4,  5,  3,  7],
      dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [116]:
np_array_1 = np.random.randint(1,20,size=(3,4))
np_array_2 = np.random.randint(1,20,size=(3,4))
print(np_array_1)
print(np_array_2)
print("Addition")
print(np_array_1 + np_array_2)
print("Subtraction")
print(np_array_1 - np_array_2)
print("Multiplication")
print(np_array_1 * np_array_2)
print("Division")
print(np_array_1 / np_array_2)


[[19  9 19  4]
 [14 16  3  9]
 [ 7  6 13 10]]
[[19 11  7 10]
 [ 5  5  4  9]
 [19  6 19 13]]
Addition
[[38 20 26 14]
 [19 21  7 18]
 [26 12 32 23]]
Subtraction
[[  0  -2  12  -6]
 [  9  11  -1   0]
 [-12   0  -6  -3]]
Multiplication
[[361  99 133  40]
 [ 70  80  12  81]
 [133  36 247 130]]
Division
[[1.         0.81818182 2.71428571 0.4       ]
 [2.8        3.2        0.75       1.        ]
 [0.36842105 1.         0.68421053 0.76923077]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [121]:
np_array = np.random.randint(1,16,size=(4,4))
print(np_array)
print(np_array.sum(axis=0))
print(np_array.sum(axis=1))

[[10  7 13 13]
 [13 11 14  6]
 [ 2  1 11  6]
 [ 6 10 15 13]]
[31 29 53 38]
[43 44 20 44]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [126]:
np_array = np.random.randint(1,20,size=(5,5))
print(np_array)
print(np.mean(np_array))
print(np.median(np_array))
print(np.std(np_array))
print(np.var(np_array))

[[ 2 18 12  7 13]
 [17  3 17  9 12]
 [ 7 19 16 19 15]
 [10  1 14 19 18]
 [ 3  4 14  8  4]]
11.24
12.0
5.928102563215315
35.142399999999995


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [128]:
np_array = np.random.randint(1,10,size=(3,3))
print(np_array)
print((np_array-np.mean(np_array))/np.std(np_array))

[[1 7 3]
 [7 7 4]
 [8 4 8]]
[[-1.88144174  0.65850461 -1.03479296]
 [ 0.65850461  0.65850461 -0.61146856]
 [ 1.081829   -0.61146856  1.081829  ]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [139]:
np_array_1 = np.random.randint(1,10,size=(3,3))
np_array_2 = np.random.randint(1,10,size=(3,))
print(np_array_1)
print(np_array_2)

print(np_array_1 + np_array_2)

[[5 9 6]
 [8 8 3]
 [3 8 5]]
[2 8 7]
[[ 7 17 13]
 [10 16 10]
 [ 5 16 12]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [147]:
np_array_1 = np.random.randint(1,10,size=(4,4))
np_array_2 = np.random.randint(1,10,size=(4,))
print(np_array_1)
print(np_array_2)
print(np_array_2[:, np.newaxis])
print(np_array_1-np_array_2[:, np.newaxis])

[[3 2 3 8]
 [8 8 8 4]
 [6 6 6 3]
 [1 8 6 4]]
[1 1 7 8]
[[1]
 [1]
 [7]
 [8]]
[[ 2  1  2  7]
 [ 7  7  7  3]
 [-1 -1 -1 -4]
 [-7  0 -2 -4]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [154]:
np_array = np.random.randint(1,10,size=(3,3))
print(np_array)
print(f"deteminant : {np.linalg.det(np_array)}")

print(f"Inverse : {np.linalg.inv(np_array)}")

print(f"Eigenvalues : {np.linalg.eigvals(np_array)}")



[[1 6 2]
 [6 7 8]
 [9 2 9]]
deteminant : 53.00000000000001
Inverse : [[ 0.88679245 -0.94339623  0.64150943]
 [ 0.33962264 -0.16981132  0.0754717 ]
 [-0.96226415  0.98113208 -0.54716981]]
Eigenvalues : [16.65064779+0.j         0.17467611+1.7755415j  0.17467611-1.7755415j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [158]:
np_array_1 = np.random.randint(1,10,size=(2,3))
np_array_2 = np.random.randint(1,10,size=(3,2))

print(np_array_1)
print(np_array_2)
print(np.dot(np_array_1,np_array_2))



[[5 5 4]
 [8 8 7]]
[[1 6]
 [9 9]
 [6 2]]
[[ 74  83]
 [122 134]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [163]:
np_array = np.random.randint(1,9,size=(3,3))
print(np_array)
np_array_1 = np_array.reshape((1,9))
print(np_array_1)
np_array_2 = np_array.reshape((9,1))
print(np_array_2)

[[4 2 4]
 [8 8 6]
 [3 6 8]]
[[4 2 4 8 8 6 3 6 8]]
[[4]
 [2]
 [4]
 [8]
 [8]
 [6]
 [3]
 [6]
 [8]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [176]:
np_array = np.random.randint(1,11,size=(5,5))
print(np_array)
np_array_flatten = np_array.flatten()
print(np_array_flatten)
np_array_final = np_array_flatten.reshape(5,5)
print(np_array_final)

[[ 8  4  1  9  8]
 [ 9  1  9 10  9]
 [ 6  1  7  3  4]
 [ 6  8  6  2  6]
 [ 4  9  5  2  2]]
[ 8  4  1  9  8  9  1  9 10  9  6  1  7  3  4  6  8  6  2  6  4  9  5  2
  2]
[[ 8  4  1  9  8]
 [ 9  1  9 10  9]
 [ 6  1  7  3  4]
 [ 6  8  6  2  6]
 [ 4  9  5  2  2]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [186]:
np_array = np.random.randint(1,30,size=(4,4))
print(np_array)
np_array[np_array>10] = 10
print(np_array)

[[11 22 10 15]
 [17 28 12 26]
 [ 4  8 23 25]
 [26 20 27  4]]
[[10 10 10 10]
 [10 10 10 10]
 [ 4  8 10 10]
 [10 10 10  4]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [202]:
schema = [('name','U10'),('age',int),('weight',float)]
data = np.array([('Hemanth',30,70.3),('Ramu',29,60.8),('Somu',33,88.3)],dtype = schema)
print(data)
sorted_1 = np.sort(data, order = 'age')
print(sorted_1)

data.sort(order = 'age')
print(data)

[('Hemanth', 30, 70.3) ('Ramu', 29, 60.8) ('Somu', 33, 88.3)]
[('Ramu', 29, 60.8) ('Hemanth', 30, 70.3) ('Somu', 33, 88.3)]
[('Ramu', 29, 60.8) ('Hemanth', 30, 70.3) ('Somu', 33, 88.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [17]:
schema = [('x','i4'),('y','i4')]
np_array = np.array([(1,2),(3,4),(5,6),(19,4)],dtype=schema)
print(np_array)

print(np_array['x'][:,np.newaxis])
print(np_array['x'])

euclidean = np.sqrt((np_array['x'][:,np.newaxis] - np_array['x'])**2 + (np_array['y'][:,np.newaxis] - np_array['y'])**2)
print(euclidean)


[( 1, 2) ( 3, 4) ( 5, 6) (19, 4)]
[[ 1]
 [ 3]
 [ 5]
 [19]]
[ 1  3  5 19]
[[ 0.          2.82842712  5.65685425 18.11077028]
 [ 2.82842712  0.          2.82842712 16.        ]
 [ 5.65685425  2.82842712  0.         14.14213562]
 [18.11077028 16.         14.14213562  0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [23]:
array = np.random.randint(1,20,size=(4,4))
print(array)

masked_array = np.ma.masked_greater(array, 10)
print(masked_array)

sum_array = masked_array.sum()
print(sum_array)

[[12 15  8  2]
 [ 5  8 17 15]
 [14 14  6 16]
 [13 17 17 18]]
[[-- -- 8 2]
 [5 8 -- --]
 [-- -- 6 --]
 [-- -- -- --]]
29


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

[[4 6 1]
 [7 4 6]
 [7 2 3]]
